import { useState } from 'react';
import { jsPDF } from 'jspdf';
import ScoreRing, { scoreColor } from '@/components/ui/ScoreRing';
import { useInterviewStore } from '@/store/interviewStore';
import { useSettingsStore } from '@/store/settingsStore';
import { SENIORITY, STAGE_LABELS, TRACK_LABELS } from '@/services/ai/prompts';
import type { InterviewReport } from '@/types';

/* ------------------------------- exporters -------------------------------- */

function bytesToBase64(bytes: Uint8Array): string {
  let bin = '';
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    bin += String.fromCharCode(...bytes.subarray(i, i + chunk));
  }
  return btoa(bin);
}

async function deliver(name: string, bytes: Uint8Array, mime: string): Promise<string> {
  if (window.mockpulse) {
    const saved = await window.mockpulse.reports.export({ name, content: bytesToBase64(bytes) });
    return saved ? `Saved to ${saved}` : 'Export cancelled.';
  }
  const copy = new Uint8Array(bytes.byteLength);
  copy.set(bytes);
  const blob = new Blob([copy.buffer], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  a.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 4000);
  return `Downloaded ${name}`;
}

function toMarkdown(r: InterviewReport): string {
  const b = r.breakdown;
  const meta = [
    `**Candidate:** ${r.candidateName}`,
    `**Role:** ${TRACK_LABELS[r.config.track]} · ${SENIORITY[r.config.seniority].title}`,
    `**Interviewer:** ${r.interviewerName}`,
    `**Date:** ${new Date(r.createdAt).toLocaleString()}`,
    `**Duration:** ${r.durationMinutes} min · ${r.questionCount} questions`,
    r.config.targetCompany ? `**Target company:** ${r.config.targetCompany}` : '',
    '',
    `**Overall score:** ${r.overallScore}/100 — ${r.grade}`,
    `**Recommendation:** ${r.recommendation}`,
    '',
    '## Scorecard',
    '',
    '| Dimension | Score |',
    '| --- | ---: |',
    `| Technical accuracy | ${b.technicalAccuracy} |`,
    `| Communication | ${b.communication} |`,
    `| Code efficiency | ${b.codeEfficiency} |`,
    `| Problem solving | ${b.problemSolving} |`,
    `| Seniority alignment | ${b.seniorityAlignment} |`,
    '',
    '## Stage breakdown',
    '',
    ...r.stageScores.map((s) => `- **${STAGE_LABELS[s.stage]} — ${s.score}/100.** ${s.notes}`),
    '',
    '## Summary',
    '',
    r.summary,
    '',
    '## Strengths',
    '',
    ...r.strengths.map((s) => `- ${s}`),
    '',
    '## Areas to improve',
    '',
    ...r.improvements.map((s) => `- ${s}`),
  ];

  const ideal =
    r.idealAnswers.length > 0
      ? ['', '## Ideal answers for missed questions', '']
      : [];
  for (const a of r.idealAnswers) {
    ideal.push(`### Q: ${a.question}`, '', a.ideal, '');
  }

  return [...meta, ...ideal, '', '---', '', '_Generated by MockPulse AI — free-tier AI remote technical interviewer._', ''].join(
    '\n',
  );
}

function buildPdf(r: InterviewReport): Uint8Array {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 52;
  const CW = W - M * 2;
  let y = M;

  const ensure = (h: number) => {
    if (y + h > H - M - 18) {
      doc.addPage();
      y = M;
    }
  };

  const text = (
    value: string,
    opts: { size?: number; style?: 'normal' | 'bold' | 'italic'; color?: [number, number, number]; gap?: number } = {},
  ) => {
    const { size = 10.5, style = 'normal', color = [30, 34, 52], gap = 6 } = opts;
    doc.setFont('helvetica', style);
    doc.setFontSize(size);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(value, CW) as string[];
    const lh = size * 1.45;
    for (const line of lines) {
      ensure(lh);
      doc.text(line, M, y + size);
      y += lh;
    }
    y += gap;
  };

  const heading = (label: string) => {
    ensure(34);
    y += 8;
    doc.setDrawColor(210, 216, 235);
    doc.line(M, y, W - M, y);
    y += 8;
    text(label.toUpperCase(), { size: 11, style: 'bold', color: [70, 112, 255], gap: 8 });
  };

  const bullets = (items: string[]) => {
    for (const item of items) text(`•  ${item}`, { size: 10.5, gap: 3 });
    y += 4;
  };

  /* header */
  doc.setFillColor(10, 14, 36);
  doc.rect(0, 0, W, 96, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('MockPulse AI — Interview Scorecard', M, 44);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(180, 190, 220);
  doc.text(
    `${r.candidateName}  ·  ${TRACK_LABELS[r.config.track]}  ·  ${SENIORITY[r.config.seniority].title}`,
    M,
    66,
  );
  doc.text(`${new Date(r.createdAt).toLocaleString()}  ·  ${r.durationMinutes} min  ·  ${r.questionCount} questions`, M, 82);
  y = 122;

  /* headline score */
  const b = r.breakdown;
  doc.setFillColor(244, 246, 252);
  doc.roundedRect(M, y, CW, 76, 10, 10, 'F');
  doc.setTextColor(20, 24, 45);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(40);
  doc.text(String(r.overallScore), M + 24, y + 52);
  doc.setFontSize(13);
  doc.text(`/100  ·  ${r.grade}`, M + 96, y + 44);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(90, 100, 130);
  doc.text(`Recommendation: ${r.recommendation.replace('-', ' ')}`, M + 96, y + 62);
  doc.setDrawColor(...scoreRGB(r.overallScore));
  doc.setFillColor(...scoreRGB(r.overallScore));
  doc.roundedRect(W - M - 150, y + 20, 126, 36, 8, 8, 'FD');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text(r.recommendation.toUpperCase().replace('-', ' '), W - M - 87, y + 43, { align: 'center' });
  y += 96;

  /* breakdown bars */
  heading('Scorecard');
  const dims: [string, number][] = [
    ['Technical accuracy', b.technicalAccuracy],
    ['Communication', b.communication],
    ['Code efficiency', b.codeEfficiency],
    ['Problem solving', b.problemSolving],
    ['Seniority alignment', b.seniorityAlignment],
  ];
  for (const [label, value] of dims) {
    ensure(30);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);
    doc.setTextColor(45, 50, 70);
    doc.text(label, M, y + 12);
    doc.setFont('helvetica', 'bold');
    doc.text(`${value}`, W - M, y + 12, { align: 'right' });

    doc.setFillColor(232, 236, 246);
    doc.roundedRect(M, y + 20, CW, 8, 4, 4, 'F');
    doc.setFillColor(...scoreRGB(value));
    doc.roundedRect(M, y + 20, Math.max(8, (CW * value) / 100), 8, 4, 4, 'F');
    y += 40;
  }

  /* stages */
  heading('Stage breakdown');
  for (const s of r.stageScores) {
    text(`${STAGE_LABELS[s.stage]} — ${s.score}/100`, { size: 11, style: 'bold', gap: 2 });
    text(s.notes || 'No notes.', { size: 10.5, color: [80, 88, 115], gap: 7 });
  }

  /* summary */
  heading('Summary');
  text(r.summary || 'No summary was produced.', { size: 10.5 });

  heading('Strengths');
  bullets(r.strengths.length ? r.strengths : ['None recorded.']);

  heading('Areas to improve');
  bullets(r.improvements.length ? r.improvements : ['None recorded.']);

  if (r.idealAnswers.length) {
    heading('Ideal answers for missed questions');
    for (const a of r.idealAnswers) {
      text(a.question, { size: 11, style: 'bold', gap: 3 });
      text(a.ideal, { size: 10.5, color: [70, 80, 110], gap: 10 });
    }
  }

  /* footer */
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(150, 156, 180);
    doc.text(`MockPulse AI · generated ${new Date(r.createdAt).toLocaleDateString()} · page ${i}/${pages}`, M, H - 24);
  }

  return new Uint8Array(doc.output('arraybuffer'));
}

function scoreRGB(v: number): [number, number, number] {
  if (v >= 85) return [56, 242, 198];
  if (v >= 70) return [70, 112, 255];
  if (v >= 55) return [245, 181, 68];
  return [251, 113, 133];
}

/* -------------------------------- screen ---------------------------------- */

const DIM_LABELS: [keyof InterviewReport['breakdown'], string][] = [
  ['technicalAccuracy', 'Technical accuracy'],
  ['communication', 'Communication'],
  ['codeEfficiency', 'Code efficiency'],
  ['problemSolving', 'Problem solving'],
  ['seniorityAlignment', 'Seniority alignment'],
];

const RECO_COLOR: Record<InterviewReport['recommendation'], string> = {
  'strong-hire': 'border-pulse-500/40 bg-pulse-500/15 text-pulse-400',
  hire: 'border-night-400/40 bg-night-500/20 text-night-200',
  'lean-hire': 'border-amber-400/40 bg-amber-400/15 text-amber-300',
  'no-hire': 'border-rose-500/40 bg-rose-500/15 text-rose-300',
};

export default function ReportScreen() {
  const report = useInterviewStore((s) => s.report);
  const busy = useInterviewStore((s) => s.busy);
  const error = useInterviewStore((s) => s.error);
  const buildReport = useInterviewStore((s) => s.buildReport);
  const reset = useInterviewStore((s) => s.reset);
  const interviewerName = useSettingsStore((s) => s.settings.interviewerName);

  const [toast, setToast] = useState('');
  const [openIdeal, setOpenIdeal] = useState<number | null>(0);

  const flash = (msg: string) => {
    setToast(msg);
    window.setTimeout(() => setToast(''), 5000);
  };

  const exportMd = async () => {
    if (!report) return;
    const name = `mockpulse-scorecard-${report.candidateName.replace(/\s+/g, '-').toLowerCase()}-${report.id}.md`;
    try {
      flash(await deliver(name, new TextEncoder().encode(toMarkdown(report)), 'text/markdown;charset=utf-8'));
    } catch (err) {
      flash(err instanceof Error ? err.message : String(err));
    }
  };

  const exportPdf = async () => {
    if (!report) return;
    const name = `mockpulse-scorecard-${report.candidateName.replace(/\s+/g, '-').toLowerCase()}-${report.id}.pdf`;
    try {
      flash(await deliver(name, buildPdf(report), 'application/pdf'));
    } catch (err) {
      flash(err instanceof Error ? err.message : String(err));
    }
  };

  /* -------------------------------- states -------------------------------- */
  if (!report) {
    return (
      <div className="flex h-full items-center justify-center px-6">
        <div className="glass max-w-md p-8 text-center">
          {busy ? (
            <>
              <div className="mx-auto mb-4 h-10 w-10 animate-spin rounded-full border-2 border-pulse-500 border-t-transparent" />
              <p className="text-sm font-semibold text-white">Crunching your performance…</p>
              <p className="mt-1.5 text-xs text-slate-400">
                Reviewing every answer against the rubric for {SENIORITY[useInterviewStore.getState().config.seniority].title} level.
              </p>
            </>
          ) : (
            <>
              <p className="text-sm font-semibold text-white">The report could not be generated</p>
              <p className="mt-1.5 text-xs leading-relaxed text-slate-400">
                {error || 'No transcript was available to score.'}
              </p>
              <div className="mt-5 flex justify-center gap-2">
                <button type="button" className="btn-primary" onClick={() => void buildReport()}>
                  Retry
                </button>
                <button type="button" className="btn-ghost" onClick={reset}>
                  Back to setup
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    );
  }

  const r = report;

  return (
    <div className="scrollbar-thin h-full overflow-y-auto px-6 py-8">
      <div className="mx-auto max-w-5xl">
        {toast && (
          <div className="mb-4 animate-fade-in-up rounded-xl border border-pulse-500/30 bg-pulse-500/10 px-4 py-3 text-[13px] text-pulse-300">
            {toast}
          </div>
        )}

        {/* header */}
        <div className="mb-6 flex flex-wrap items-end justify-between gap-4">
          <div>
            <div className="mb-2 flex items-center gap-2">
              <span className="chip !border-pulse-500/30 !bg-pulse-500/10 !text-pulse-400">Debrief</span>
              <span className="chip">{TRACK_LABELS[r.config.track]}</span>
              <span className="chip">{SENIORITY[r.config.seniority].title}</span>
            </div>
            <h1 className="text-3xl font-extrabold tracking-tight text-white">
              {r.candidateName}&apos;s scorecard
            </h1>
            <p className="mt-1 text-sm text-slate-400">
              Interviewed by {r.interviewerName || interviewerName} · {new Date(r.createdAt).toLocaleString()} ·{' '}
              {r.durationMinutes} min · {r.questionCount} questions
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <button type="button" className="btn-ghost" onClick={() => void exportMd()}>
              Export Markdown
            </button>
            <button type="button" className="btn-ghost" onClick={() => void exportPdf()}>
              Export PDF
            </button>
            <button type="button" className="btn-primary" onClick={reset}>
              New interview
            </button>
          </div>
        </div>

        {/* hero */}
        <div className="glass mb-6 grid gap-6 p-6 sm:grid-cols-[auto_1fr] sm:items-center">
          <div className="flex justify-center">
            <ScoreRing value={r.overallScore} size={150} stroke={13} label="overall" sublabel="/ 100" />
          </div>
          <div className="min-w-0">
            <div className="mb-3 flex flex-wrap items-center gap-2.5">
              <span className="rounded-lg bg-gradient-to-r from-night-500 to-night-700 px-3 py-1.5 text-[13px] font-bold text-white">
                {r.grade}
              </span>
              <span className={`rounded-lg border px-3 py-1.5 text-[13px] font-bold uppercase tracking-wide ${RECO_COLOR[r.recommendation]}`}>
                {r.recommendation.replace('-', ' ')}
              </span>
              {r.config.targetCompany && (
                <span className="chip">Targeting {r.config.targetCompany}</span>
              )}
            </div>
            <p className="text-[14px] leading-relaxed text-slate-300">{r.summary}</p>
          </div>
        </div>

        {/* breakdown + stages */}
        <div className="mb-6 grid gap-6 lg:grid-cols-2">
          <section className="glass p-5">
            <h2 className="mb-4 text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">
              Dimension breakdown
            </h2>
            <div className="space-y-3.5">
              {DIM_LABELS.map(([key, label]) => {
                const v = r.breakdown[key];
                return (
                  <div key={key}>
                    <div className="mb-1.5 flex items-baseline justify-between">
                      <span className="text-[13px] text-slate-300">{label}</span>
                      <span className="text-[13px] font-bold tabular-nums text-white">{v}</span>
                    </div>
                    <div className="h-2 overflow-hidden rounded-full bg-white/8">
                      <div
                        className="h-full rounded-full transition-all duration-1000"
                        style={{ width: `${v}%`, background: scoreColor(v) }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          </section>

          <section className="glass p-5">
            <h2 className="mb-4 text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">
              Stage-by-stage performance
            </h2>
            <div className="space-y-3">
              {r.stageScores.length === 0 && (
                <p className="text-[13px] text-slate-500">No stage scores were recorded.</p>
              )}
              {r.stageScores.map((s) => (
                <div key={s.stage} className="rounded-xl border border-white/10 bg-white/[0.03] px-4 py-3">
                  <div className="flex items-center justify-between gap-3">
                    <span className="text-[13px] font-semibold text-white">{STAGE_LABELS[s.stage]}</span>
                    <span
                      className="rounded-md px-2 py-0.5 text-[12px] font-bold tabular-nums"
                      style={{ color: scoreColor(s.score), background: `${scoreColor(s.score)}1f` }}
                    >
                      {s.score}
                    </span>
                  </div>
                  {s.notes && <p className="mt-1 text-[12px] leading-relaxed text-slate-400">{s.notes}</p>}
                </div>
              ))}
            </div>
          </section>
        </div>

        {/* strengths / improvements */}
        <div className="mb-6 grid gap-6 md:grid-cols-2">
          <section className="glass p-5">
            <h2 className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-pulse-400">
              <span className="h-1.5 w-1.5 rounded-full bg-pulse-400" /> What you did well
            </h2>
            <ul className="space-y-2.5">
              {r.strengths.length === 0 && <li className="text-[13px] text-slate-500">Nothing recorded.</li>}
              {r.strengths.map((s, i) => (
                <li key={i} className="flex gap-2.5 text-[13px] leading-relaxed text-slate-300">
                  <span className="mt-0.5 text-pulse-400">✓</span>
                  {s}
                </li>
              ))}
            </ul>
          </section>

          <section className="glass p-5">
            <h2 className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-amber-300">
              <span className="h-1.5 w-1.5 rounded-full bg-amber-300" /> Where to improve
            </h2>
            <ul className="space-y-2.5">
              {r.improvements.length === 0 && <li className="text-[13px] text-slate-500">Nothing recorded.</li>}
              {r.improvements.map((s, i) => (
                <li key={i} className="flex gap-2.5 text-[13px] leading-relaxed text-slate-300">
                  <span className="mt-0.5 text-amber-300">→</span>
                  {s}
                </li>
              ))}
            </ul>
          </section>
        </div>

        {/* ideal answers */}
        {r.idealAnswers.length > 0 && (
          <section className="glass mb-8 p-5">
            <h2 className="mb-4 text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">
              Ideal answers for the questions you missed
            </h2>
            <div className="space-y-2">
              {r.idealAnswers.map((a, i) => {
                const open = openIdeal === i;
                return (
                  <div key={i} className="overflow-hidden rounded-xl border border-white/10 bg-white/[0.03]">
                    <button
                      type="button"
                      className="flex w-full items-center justify-between gap-3 px-4 py-3 text-left hover:bg-white/[0.05]"
                      onClick={() => setOpenIdeal(open ? null : i)}
                    >
                      <span className="text-[13px] font-medium text-slate-200">{a.question}</span>
                      <span className="text-[11px] text-slate-500">{open ? '−' : '+'}</span>
                    </button>
                    {open && (
                      <p className="whitespace-pre-wrap border-t border-white/8 bg-black/25 px-4 py-3.5 text-[13px] leading-relaxed text-slate-300">
                        {a.ideal}
                      </p>
                    )}
                  </div>
                );
              })}
            </div>
          </section>
        )}

        <p className="pb-2 text-center text-[11px] text-slate-600">
          Generated locally by MockPulse AI · scores come from your transcript, never from a third party
        </p>
      </div>
    </div>
  );
}
